apiVersion: v1
kind: Pod
metadata:
  name: trino-basic
  namespace: trino-simplified
  labels:
    app: trino
spec:
  containers:
    - name: trino
      image: trinodb/trino:latest
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1000m"
      ports:
        - containerPort: 8080
      command: ["/usr/lib/trino/bin/run-trino"]
      env:
        - name: JAVA_OPTS
          value: "-Xmx2G -Xms1G"
          