apiVersion: v1
data:
  access-control.properties: |
    access-control.name=file
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    query.max-memory=1GB
    query.max-memory-per-node=512MB
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    http-server.authentication.type=PASSWORD
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/etc/trino/users.properties
  users.properties: |
    admin=password123
    analyst=readme
  catalog-s3.properties: |
    connector.name=hive
    hive.s3.aws-access-key=x00jlqcW2EMuzsk9FVs4
    hive.s3.aws-secret-key=LdtcxOrNitCcc0j2zuqCPk5Ncb6bGd4ZLlad1mjt
    hive.s3.endpoint=http://minio.trino-simplified.svc.cluster.local:9000
    hive.s3.path-style-access=true
    hive.metastore=filesystem
    hive.metastore.catalog.dir=s3a://trino-bucket/
kind: ConfigMap
metadata:
  name: trino-config
  namespace: trino-simplified
kind: ConfigMap
metadata:
  name: trino-config
  namespace: trino-simplified